services:
  backend:
    build:
      context: ./backend
    environment:
      NOVELFABRIC_BACKEND_BIND_ADDRESS: 0.0.0.0:50000
      NOVELFABRIC_DATA_DIR: /app/data
    volumes:
      - ./data:/app/data
    ports:
      - "50000:50000"

  frontend:
    build:
      context: ./frontend
    ports:
      - "50001:80"
    depends_on:
      - backend
